config/routes.rb
Rails.application.routes.draw do
  get 'welcome/welcome'

  get 'pages/api'

  get 'store/index'

  get '/api' => 'pages#api'

  resources :phosphos

  resources :chloros

  resources :secchis

  resources :lakes

  root 'store#index' 

end

app/models/chloro.rb
class Chloro < ActiveRecord::Base
	belongs_to :secchi_depth
	belongs_to :lake
end

app/controllers/chloros_controller.rb
class ChlorosController < ApplicationController
  before_action :set_chloro, only: [:show, :edit, :update, :destroy]
  before_action :all_chloros, only: [:show, :index, :create, :destroy, :update]

  respond_to :html, :js
  # GET /chloros
  # GET /chloros.json
  def all_chloros
    @chloros = Chloro.order("created_at DESC")
  end


  def index
    @chloros = Chloro.order("created_at DESC")
  end

  # GET /chloros/1
  # GET /chloros/1.json
  def show
  end

  # GET /chloros/new
  def new
      @chloro = Chloro.new
      @lake = Lake.find(params[:lake_id])
      @chloro.lake_id = params[:lake_id]
  end

  # GET /chloros/1/edit
  def edit
  end

  # POST /chloros
  # POST /chloros.json
  def create
    @chloro = Chloro.new(chloro_params)
    @chloro.save!
    flash.now[:notice] = 'Chlorophyll was successfully created'

    respond_to do |format|
      format.js
      format.json { render :show, status: :created, location: @chloro }
    end
  end

  # PATCH/PUT /chloros/1
  # PATCH/PUT /chloros/1.json
  def update
    @chloro.update!(chloro_params)
    flash.now[:notice] = 'Chlorophyll sample was successfully updated.'
        respond_to do |format|
      format.js
      format.json { render :show, status: :created, location: @chloro }
    end
  end

  # DELETE /chloros/1
  # DELETE /chloros/1.json
  def destroy
    flash.now[:notice] = 'Chlorophyll sample was destroyed.'
    @chloro.destroy
    respond_to do |format|
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chloro
      @chloro = Chloro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chloro_params
      params.require(:chloro).permit(:sample_time, :event, :comp_sample_depth,
        :weather, :comments, :secchi_id, :lake_id)
    end
end

app/helpers/chloros_helper.rb
module ChlorosHelper
end

app/views/chloros/_chloro.html.erb
      <tr data-toggle="collapse" data-target=".sample<%=chloro.id%>">

        <td>
          <div class="btn-group-vertical">
            <button type='button' class='btn btn-info' data-toggle='collapse' data-target=".sample<%=chloro.id%>">Details</button>
            <%= link_to 'Edit', edit_chloro_path(chloro, :lake_id => chloro.lake_id),  class: 'btn btn-mini btn btn-warning', remote: true  %>            <%= link_to 'Destroy', chloro, class: 'btn btn-mini btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
          </div>
        </td>


        <td> <%= Lake.find(chloro.lake_id).lkname %> </td>
        <td> <%= chloro.sample_time.to_s(:short) %> </td>


      </tr>
      <tr>
        <%=render 'show', :chloro => chloro %>
      </tr>

app/views/chloros/_form.html.erb
<%= form_for(@chloro, remote: true ) do |f| %>
  
  <div class="field">
    <%= f.label :lake_id %><br>
    <%= f.select :lake_id, options_for_select(Lake.all.collect {|l| ["#{l.lkname}", l.id]}, selected: (@chloro.lake ? @chloro.lake.id : Lake.first.id)), {} %>
  </div>

  <div class="field">
    <%= f.label :sample_time %><br>
    <%= f.datetime_select :sample_time %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.select :event, {"May"=> 1, "June"=>2, "July"=>3, "August"=>4, "September"=> 5}%>
  </div>
  <div class="field">
    <%= f.label :comp_sample_depth %><br>
    <%= f.text_field :comp_sample_depth%>
  </div>



  <div class="field">
    <%= f.label :secchi_id, "Linked to Secchi" %><br>
    <%= f.select :secchi_id, options_for_select(Secchi.where(lake_id: params[:lake_id]).collect {|s| ["#{Lake.find(params[:lake_id]).lkname } on  #{s.sample_time.to_s(:long)}", s.id]}, selected: (Secchi.where(lake_id: params[:lake_id]).last.id)),{} %>
  </div>

  <div class="field">
    <%= f.label :weather %><br>
    <%= f.select :weather, {"Sunny"=> 1, "Partly Cloudy"=>2, "Overcast"=>3, "Foggy"=> 4}%>
  </div>
    <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
    <%= link_to 'Cancel', :back, :class=>'btn btn-default' %>
  </div>

<% end %>

app/views/chloros/_show.html.erb
<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Lake id:<div></strong></td>
  <td class="hiddenRow" colspan="3"><div class="collapse sample<%=chloro.id%>" ><%= chloro.lake_id %></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Created at:<div></strong></td>
  <td class="hiddenRow" colspan="3"><div class="collapse sample<%=chloro.id%>" ><%= chloro.created_at.to_s(:long) %></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Updated at:<div></strong></td>
  <td class="hiddenRow" colspan="3"><div class="collapse sample<%=chloro.id%>" ><%= chloro.updated_at.to_s(:long) %></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Weather:</div></strong></td>
  <td class="hiddenRow"><div class="collapse sample<%=chloro.id%>" ><%= weather_text(chloro.weather)%></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Comments:</div></strong></td>
  <td class="hiddenRow"><div class="collapse sample<%=chloro.id%>" ><%= chloro.comments%></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Event:</div></strong></td>
  <td class="hiddenRow"><div class="collapse sample<%=chloro.id%>" ><%= chloro.event%></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Composite Sample Depth:</div></strong></td>
  <td class="hiddenRow"><div class="collapse sample<%=chloro.id%>" ><%= chloro.comp_sample_depth%></div></td>
</tr>

<tr>
  <td class="hiddenRow"><strong><div class="collapse sample<%=chloro.id%>" >Linked to Secchi:</div></strong></td>
  <td class="hiddenRow" colspan="3"><div class="collapse sample<%=chloro.id%>" ><%= Secchi.find(chloro.secchi_id).sample_time.to_s(:long)%></div></td>
</tr>

app/views/chloros/create.js.erb
$('#sample-form').slideUp(350);

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
 
<% end %>

app/views/chloros/destroy.js.erb
$('#chloros').html("<%= j (render @chloros) %>");

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
 
<% end %>

app/views/chloros/edit.html.erb
<% @page_title = "Edit Chlorophyll" %>
<h1>Editing Chloro</h1>

<%= render 'form' %>

<%= link_to 'Show', @chloro %> |
<%= link_to 'Back', chloros_path %>

app/views/chloros/edit.js.erb
$('#sample-form').html("<%= j (render 'form') %>");
$('#sample-form').slideDown(350);

app/views/chloros/index.html.erb
<% @page_title = "Chlorophyll Samples" %>

<div class="media">
<div class="media-body">
<div id="sample-form", style="display:none;"></div>
<div class="page-header">
<h1>Chlorophyll Samples</h1>
<%= link_to 'New Chloro', :root, class: 'new-button btn btn-mini btn-success'%>
</div>

<table class="table table-condensed" style="collapse;">
<col width="100">
  <thead>
    <tr>
      <th></th>
      <th>Lake</th>
      <th>Time</th>
    </tr>
  </thead>

  <tbody id="chloros">
    <%= render @chloros %>
  </tbody>
</table>

</div>
</div>

app/views/chloros/new.html.erb
<h1>New Chloro</h1>

<%= render 'form' %>

<%= link_to 'Back', chloros_path %>

app/views/chloros/new.js.erb
<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
 
<% end %>

$('#sample-form').html("<%= j (render 'chloros/form') %>");
$('#sample-form').slideDown(350);
$("html, body").animate({ scrollTop: 0 }, "slow");

app/views/chloros/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chloro_path(@chloro) %> |
<%= link_to 'Back', chloros_path %>

app/views/chloros/update.js.erb
$('#sample-form').slideUp(350);

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
<% end %>

$('#chloros').html("<%= j (render @chloros)%> ");