config/routes.rb
Rails.application.routes.draw do
  get 'welcome/welcome'

  get 'pages/api'

  get 'store/index'

  get '/api' => 'pages#api'

  resources :phosphos

  resources :chloros

  resources :secchis

  resources :lakes

  root 'store#index' 

end

app/models/lake.rb
class Lake < ActiveRecord::Base
	has_many :secchis, dependent: :destroy
	has_many :phosphos, dependent: :destroy
end

app/controllers/lakes_controller.rb
class LakesController < ApplicationController
  before_action :set_lake, only: [:show, :edit, :update, :destroy]

  # GET /lakes
  # GET /lakes.json
  def index
    @lakes = Lake.all
  end

  # GET /lakes/1
  # GET /lakes/1.json
  def show
  end

  # GET /lakes/new
  def new
    @lake = Lake.new
  end

  # GET /lakes/1/edit
  def edit
  end

  # POST /lakes
  # POST /lakes.json
  def create
    @lake = Lake.new(lake_params)

    respond_to do |format|
      if @lake.save
        format.html { redirect_to @lake, notice: 'Lake was successfully created.' }
        format.json { render :show, status: :created, location: @lake }
      else
        format.html { render :new }
        format.json { render json: @lake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lakes/1
  # PATCH/PUT /lakes/1.json
  def update
    respond_to do |format|
      if @lake.update(lake_params)
        format.html { redirect_to @lake, notice: 'Lake was successfully updated.' }
        format.json { render :show, status: :ok, location: @lake }
      else
        format.html { render :edit }
        format.json { render json: @lake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lakes/1
  # DELETE /lakes/1.json
  def destroy
    @lake.destroy
    respond_to do |format|
      format.html { redirect_to lakes_url, notice: 'Lake was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lake
      @lake = Lake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lake_params
      params.require(:lake).permit(:lkname)
    end
end

app/helpers/lakes_helper.rb
module LakesHelper
end

app/views/lakes/_form.html.erb
<%= form_for(@lake) do |f| %>
  <% if @lake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lake.errors.count, "error") %> prohibited this lake from being saved:</h2>

      <ul>
      <% @lake.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lkname %><br>
    <%= f.text_field :lkname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lakes/edit.html.erb
<h1>Editing Lake</h1>

<%= render 'form' %>

<%= link_to 'Show', @lake %> |
<%= link_to 'Back', lakes_path %>

app/views/lakes/index.html.erb
<% @page_title = "Lake List" %>
<!-- <p id="notice"><%= notice %></p> -->

<h1>Lakes</h1>
<div class="media">
<div class="media-body">
<table class="table table-responsive">
  <thead>
    <tr>
      <th>Lkname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lakes.each do |lake| %>
      <tr>
        <td><%= lake.lkname %></td>
        <td><%= link_to 'Show', lake, class: 'btn btn-mini btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_lake_path(lake), class: 'btn btn-mini btn btn-warning' %></td>
        <td><%= link_to 'Destroy', lake, class: 'btn btn-mini btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Lake', new_lake_path %>

app/views/lakes/new.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Lkname:</strong>
  <%= @lake.lkname %>
</p>

<%= link_to 'Edit', edit_lake_path(@lake) %> |
<%= link_to 'Back', lakes_path %>

app/views/lakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lkname:</strong>
  <%= @lake.lkname %>
</p>

<%= link_to 'Edit', edit_lake_path(@lake) %> |
<%= link_to 'Back', lakes_path %>