config/routes.rb
Rails.application.routes.draw do
  get 'welcome/welcome'

  get 'pages/api'

  get 'store/index'

  get '/api' => 'pages#api'

  resources :phosphos

  resources :chloros

  resources :secchis

  resources :lakes

  root 'store#index' 

end

app/models/secchi.rb
class Secchi < ActiveRecord::Base
	belongs_to :lake
	has_one :chloro, dependent: :destroy
end

app/controllers/secchis_controller.rb
class SecchisController < ApplicationController
  before_action :set_secchi, only: [:show, :edit, :update, :destroy]
  before_action :all_secchis, only: [:show, :index, :create, :destroy, :update]
  respond_to :html, :js


  def all_secchis
    @secchis = Secchi.order("created_at DESC")
  end

  # GET /secchis
  # GET /secchis.json

  def index
    @secchis = Secchi.order("created_at DESC")
  end

  # GET /secchis/1
  # GET /secchis/1.json
  def show
    @secchi = Secchi.find(params[:id])
  end

  # GET /secchis/new
  def new
    @secchi = Secchi.new
    @lake = Lake.find(params[:lake_id])
    @secchi.lake_id = params[:lake_id]
  end

  # GET /secchis/1/edit
  def edit
  end

  # POST /secchis
  # POST /secchis.json
  def create

    @secchi = Secchi.new(secchi_params)
    @secchi.save!

    flash.now[:notice] = 'Secchi depth was successfully saved.'

    respond_to do |format|
      format.js
      format.json { render :show, status: :created, location: @secchi }
    end
  end

  # PATCH/PUT /secchis/1
  # PATCH/PUT /secchis/1.json
  def update
    @secchi.update!(secchi_params)
    flash.now[:notice] = 'Secchi depth was successfully updated.'
        respond_to do |format|
      format.js
      format.json { render :show, status: :ok, location: @secchi }
    end
  end

  # DELETE /secchis/1
  # DELETE /secchis/1.json
  def destroy
    @secchi.destroy
    flash.now[:notice] = 'Secchi depth was destroyed.'
    respond_to do |format|
      format.js
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secchi
      @secchi = Secchi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secchi_params
      params.require(:secchi).permit(:sample_time, :weather, :comments,
        :lake_id, :secchi_depth_ft)
    end
end

app/helpers/secchis_helper.rb
module SecchisHelper
end

app/views/secchis/_form.html.erb
<%= form_for(@secchi, remote: true) do |f| %>
  
  <div class="field">
    <%= f.label :lake_id %><br>
    <%= f.select :lake_id, options_for_select(Lake.all.collect {|l| ["#{l.lkname}", l.id]}, selected: (@secchi.lake ? @secchi.lake.id : Lake.first.id)), {} %>
  </div>

  <div class="field">
    <%= f.label :sample_time %><br>
    <%= f.datetime_select :sample_time %>
  </div>
  
  <div class="field">
    <%= f.label :secchi_depth_ft %><br>
    <%= f.text_field :secchi_depth_ft %>
  </div>
  <div class="field">
    <%= f.label :weather %><br>
    <%= f.select :weather, {"Sunny"=> 1, "Partly Cloudy"=>2, "Overcast"=>3, "Foggy"=> 4}%>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
    <%= link_to 'Cancel', :back, :class=>"btn btn-default"%>
  </div>
<% end %>

app/views/secchis/_secchi.html.erb
    <tr data-toggle="collapse" data-target=".sample<%=secchi.id%>">
      <td><div class="btn-group-vertical">
        <button type='button' class='btn btn-info' data-toggle='collapse' data-target=".sample<%=secchi.id%>">Details</button>


        <%= link_to 'Edit', edit_secchi_path(secchi), class: 'btn btn-mini btn btn-warning', remote: true %>


        <%= link_to 'Destroy', secchi, class: 'btn btn-mini btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }, remote: true%>
      </div></td>

      <td><%= Lake.find(secchi.lake_id).lkname %> </td>
      <td><%= secchi.sample_time.to_s(:short) %></td>
    </tr>

    <tr>
      <%=render 'show', :secchi => secchi %>
    </tr>

app/views/secchis/_show.html.erb
<tr>
	<td class="hiddenRow"><strong><div class="collapse sample<%=secchi.id%>" >Secchi depth:</div></strong></td>

	<td class="hiddenRow"><div class="collapse sample<%=secchi.id%>" ><%= secchi.secchi_depth_ft %></div></td>
<tr>
	<td class="hiddenRow"><strong><div class="collapse sample<%=secchi.id%>" >Weather:</div></strong></td>
  	<td class="hiddenRow"><div class="collapse sample<%=secchi.id%>" ><%= weather_text(secchi.weather)%></div></td>
</tr>

</tr>

<tr>
	<td class="hiddenRow"><strong><div class="collapse sample<%=secchi.id%>" >Comments:</div></strong></td>
  	<td class="hiddenRow" colspan="3"><div class="collapse sample<%=secchi.id%>" ><%= secchi.comments%></div></td>
</tr>

<tr>
	<td class="hiddenRow"><strong><div class="collapse sample<%=secchi.id%>" >Created at:<div></strong></td>
  	<td class="hiddenRow" colspan="3"><div class="collapse sample<%=secchi.id%>" ><%= secchi.created_at.to_s(:long) %></div></td>
</tr>

<tr>
	<td class="hiddenRow"><strong><div class="collapse sample<%=secchi.id%>" >Updated at:<div></strong></td>
  	<td class="hiddenRow" colspan="3"><div class="collapse sample<%=secchi.id%>" ><%= secchi.updated_at.to_s(:long) %></div></td>
</tr>

    

app/views/secchis/create.js.erb
$('#sample-form').slideUp(350);

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
 
<% end %>

app/views/secchis/destroy.js.erb
$('#secchis').html("<%= j (render @secchis) %>");

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
 
<% end %>

app/views/secchis/edit.html.erb
<% @page_title = "Edit Secchi Depth" %>
<h1>Editing Secchi Depth</h1>

<%= render 'form' %>

<%= link_to 'Show', @secchi %> |
<%= link_to 'Back', secchis_path %>

app/views/secchis/edit.js.erb
$('#sample-form').html("<%= j (render 'form') %>");
$('#sample-form').slideDown(350);

app/views/secchis/index.html.erb
<% @page_title = "Secchi Depth Samples" %>

<div class="media">
<div class="media-body">
<div id="sample-form", style="display:none;"></div>
<div class="page-header">
  <h1>Secchi Samples</h1>
  <%= link_to 'New Secchi Depth', :root, class: 'new-button btn btn-mini btn btn-success'  %>
</div>


<table class="table" style="collapse;">
<col width="100">
  <thead>
    <tr>
      <th></th>
      <th> Lake </th>
      <th> Time </th>
      
    </tr>
  </thead>
  <tbody id="secchis">
    <%= render @secchis %>
  </tbody>
</table>
</div>
</div>

<br>

app/views/secchis/new.html.erb
<h1>New Secchi Depth</h1>

<%= render 'form' %>

<%= link_to 'Back', secchis_path %>

app/views/secchis/new.js.erb
$('#sample-form').html("<%= j (render 'secchis/form') %>");
$('#sample-form').slideDown(350);
$("html, body").animate({ scrollTop: 0 }, "slow");

app/views/secchis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @secchi.sample_time %>
</p>

<p>
  <strong>Data:</strong>
  <%= @secchi.secchi_depth_ft %>
</p>

<%= link_to 'Edit', edit_secchi_path(@secchi) %> |
<%= link_to 'Back', secchis_path %>

app/views/secchis/show.js.erb
$('#sample-form').html("<%= j(render 'show') %>");
$('#sample-form').slideDown(350);

app/views/secchis/update.js.erb
$('#sample-form').slideUp(350);

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>")
  $("#flash_messages").attr("id","notice")
  $("#notice").show().hide(2000)
<% end %>

$('#secchis').html("<%= j (render @secchis)%> ");