config/routes.rb
Rails.application.routes.draw do
  get 'welcome/welcome'

  get 'pages/api'

  get 'store/index'

  get '/api' => 'pages#api'

  resources :phosphos

  resources :chloros

  resources :secchis

  resources :lakes

  root 'store#index' 

end

app/views/layouts/_flash_notices.html.erb
<div id="flash_messages">
  <% flash.each do |type, message| %>
    <p><%= type %>: <%= message %></p>
  <% end %>

  <% flash.clear %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Waterlog | <%= @page_title %> </title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="wrap">
<div class='container-fluid'>


				<ul class="nav nav-tabs nav-justified">

					<li><%=link_to "Home", store_index_path %></li>
					<li><%=link_to "Secchi", secchis_path%></li>
					<li><%=link_to "Chlorophyll", chloros_path%></li>
					<li><%=link_to "Phosphorus", phosphos_path%></li>
				</ul>

			<%= render 'layouts/flash_notices'%> 
			
			<div class='container-fluid'>

			<%= yield %>

			</div>


		
</div>
</div>
<hr/>
<br/>
<div id="footer">
	<div class="container">
		<p class="muted credit">For Developers: <%=link_to "RESTful API", api_path%></p>
	</div>
</div>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaterLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
		<div id="main">
			<%= yield %>
		</div>
</body>
</html>